"""アプリケーション共通の定数を定義するモジュール."""

# カメラデフォルト設定 (camera_setup.py)
DEFAULT_CAMERA_WIDTH = 640
DEFAULT_CAMERA_HEIGHT = 480
DEFAULT_CAMERA_FPS = 30

# プレビューサイズ (viewer.py, run.py)
DEFAULT_PREVIEW_WIDTH = 1280
DEFAULT_PREVIEW_HEIGHT = 720

# FHD (Full HD) サイズ (fft.py)
FHD_WIDTH = 1920
FHD_HEIGHT = 1080

# 推論 API 設定 (inference)
DEFAULT_INFER_CONFIG_PATH = "config/infer_config.json"
DEFAULT_INFERENCE_TIMEOUT = 5.0
DEFAULT_INFERENCE_FORMAT = "jpeg"

# 検出 API 設定 (detection)
DEFAULT_DETECT_CONFIG_PATH = "config/detect_config.json"
DEFAULT_DETECTION_TIMEOUT = 5.0
DEFAULT_DETECTION_FORMAT = "raw"
DEFAULT_DETECTION_SCORE_THRESHOLD = 0.5
DEFAULT_DETECTION_JPEG_QUALITY = 90
DEFAULT_DETECTION_FPS = 5.0

# FFT フィルタ設定 (fft.py)
FFT_FILTER_RADIUS_MAX = 200
FFT_FILTER_RADIUS_MIN = 10
FFT_FILTER_RADIUS_STEP = 10
